import json
import urllib.request
import urllib.error
import os

SLACK_WEBHOOK_URL = os.environ.get("SLACK_WEBHOOK_URL")

def send_slack_alert(anomaly_count, incident_report):
    """
    Send a formatted incident alert to Slack channel.
    Called automatically by summarizer.py when anomalies are detected.
    """
    if not SLACK_WEBHOOK_URL:
        print("⚠️  SLACK_WEBHOOK_URL not set — skipping Slack alert")
        return

    # Format message with Slack markdown
    message = {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": "🚨 AUTOMATED INCIDENT ALERT"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Anomalies Detected:*\n{anomaly_count} flagged entries"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Status:*\n🔴 Action Required"
                    }
                ]
            },
            {
                "type": "divider"
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*AI Incident Summary:*\n{incident_report[:1000]}\n\n_Full report saved to logs/incident_report.txt_"
                }
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "🤖 Generated by AI Log Anomaly Detector | Powered by Claude AI"
                    }
                ]
            }
        ]
    }

    data = json.dumps(message).encode("utf-8")
    req = urllib.request.Request(
        SLACK_WEBHOOK_URL,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST"
    )

    try:
        with urllib.request.urlopen(req) as response:
            if response.status == 200:
                print("✅ Slack alert sent successfully!")
            else:
                print(f"⚠️  Slack returned status: {response.status}")
    except urllib.error.HTTPError as e:
        print(f"❌ Slack alert failed: {e.code} {e.read().decode()}")
